default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: qna_development
  host: localhost
  username: amir
  password: <%= ENV.fetch("PG_PASSWORD") %>

test:
  <<: *default
  database: qna_test
  host: localhost
  username: amir
  password: <%= ENV.fetch("PG_PASSWORD") %>
  

production:
  <<: *default
  database: qna_production